kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: koncepts
  labels:
    app: koncepts
spec:
  to:
    kind: Service
    name: koncepts
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
