language: python

services:
  - docker

python:
  - 3.8

git:
  depth: 3

install:
  - docker container run --rm --privileged multiarch/qemu-user-static --reset -p yes
  #- docker container run -d --rm --name buildkitd --privileged moby/buildkit:latest
  #- sudo docker container cp buildkitd:/usr/bin/buildctl /usr/local/bin/
  #- export BUILDKIT_HOST="docker-container://buildkitd"

env:
  global:
    - TRAVIS_COMMIT_SHORT=$(echo $TRAVIS_COMMIT | cut -c-7)

script:
  - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
  - DOCKER_CLI_EXPERIMENTAL=enabled DOCKER_BUILDKIT=1 docker build -t srowley/python-demo:latest -t srowley/python-demo:$TRAVIS_COMMIT_SHORT --platform linux/arm/v7,linux/arm64,linux/amd64 .
