language: python

services:
  - docker

python:
  - 3.8

git:
  depth: 3

install:
  - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

env:
  global:
    - TRAVIS_COMMIT_SHORT=$(echo $TRAVIS_COMMIT | cut -c-7)

script:
  - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
  - docker build -t srowley/python-demo:latest -t srowley/python-demo:$TRAVIS_COMMIT_SHORT --progress plain --platform linux/arm/v7,linux/arm64,linux/amd64 --push .
