dist: xenial
sudo: required

language: python

python:
  - 3.8

git:
  depth: 3

before_install:
  - curl -fsSL https://get.docker.com | sh
  - echo '{"experimental":"enabled"}' | sudo tee /etc/docker/daemon.json
  - mkdir -p $HOME/.docker
  - echo '{"experimental":"enabled"}' | sudo tee $HOME/.docker/config.json
  - sudo service docker start
install:
  - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
  - docker buildx create --name xbuilder --use

env:
  global:
    - TRAVIS_COMMIT_SHORT=$(echo $TRAVIS_COMMIT | cut -c-7)

script:
  - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
  - docker buildx build -t srowley/python-demo:$TRAVIS_COMMIT_SHORT --progress plain --platform linux/arm/v7,linux/amd64 --push .
  - docker images
  - docker run -d -p 8080:8080 --name python-demo srowley/python-demo:$TRAVIS_COMMIT_SHORT
  - docker ps | grep -q python-demo
