language: python

python:
  - 3.8

git:
  depth: 3

service:
  - docker

install: skip

env:
  global:
    - TRAVIS_COMMIT_SHORT=$(echo $TRAVIS_COMMIT | cut -c-7)

script:
  - docker buildx build -t srowley/python-demo:$TRAVIS_COMMIT_SHORT --platform linux/arm32,linux/amd64 .
  - docker run -d -p 8080:8080 --name python-demo srowley/python-demo:$TRAVIS_COMMIT_SHORT
  - docker ps | grep -q python-demo
