apiVersion: apps/v1
kind: Deployment
metadata:
  name: koncepts-demo
  labels:
    app: koncepts-demo
spec:
  strategy:
    type: RollingUpdate
  triggers:
  replicas: 1
  selector:
    matchLabels:
      app: koncepts-demo
  template:
    metadata:
      labels:
        app: koncepts-demo
    spec:
      containers:
        - name: koncepts
          image: srowley/koncepts:latest
          ports:
            - containerPort: 8080
              protocol: TCP
          imagePullPolicy: Always
          volumeMounts:
            - name: config
              mountPath: /usr/local/etc/content
      volumes:
        - name: config
          configMap:
            name: myapp-config

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: koncepts-demo
  name: koncepts-demo
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector:
    app: koncepts-demo
