kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: koncepts
spec:
  rules:
  - host: koncepts.shaner.io
    http:
      paths:
      - pathType: ImplementationSpecific
        backend:
          service:
            name: koncepts
            port:
              number: 8080
