apiVersion: apps/v1
kind: Deployment
metadata:
  name: koncepts
spec:
  template:
    spec:
      containers:
      - name: koncepts
        volumeMounts:
        - name: config-volume
          mountPath: /usr/local/etc/content
      volumes:
      - name: config-volume
        configMap:
          name: config-files