name: build

on:
  push:
    branches:
    - main
    paths:
    - content/**
    - Dockerfile
    - src/**
    - requirements.txt
    - .github/**

jobs:

  build:

    runs-on: ubuntu-latest
    container:
      image: quay.io/srowley/multiarch-build:latest
      env:
        IMAGE_NAME: koncepts

    steps:
    - uses: actions/checkout@v3
    - name: build
      run: |
        echo Hello!
        export REPO_NAME=srowley/$IMAGE_NAME:latest
        export COMMIT_SHA_SHORT=$(echo $GITHUB_SHA | cut -c-7)

        echo ${{secrets.DOCKERHUB_PASSWORD}} | buildah login -u ${{secrets.DOCKERHUB_USERNAME}} docker.io --password-stdin
        echo ${{secrets.QUAY_PASSWORD}} | buildah login -u ${{secrets.QUAY_USERNAME}} quay.io --password-stdin

        buildah manifest create koncepts

        buildah --storage-drive=vfs bud \
          --tag quay.io/$REPO_NAME \
          --manifest koncepts \
          --arch amd64 \
          --file Dockerfile \
          --build-arg VCS_REF=$COMMIT_SHA_SHORT \
          --build-arg BUILD_DATE=$(date -u +"%Y-%m-%dT%TZ") \
          /github/home

        buildah --storage-drive=vfs bud \
          --tag quay.io/$REPO_NAME \
          --manifest koncepts \
          --arch arm \
          --file Dockerfile \
          --build-arg VCS_REF=$COMMIT_SHA_SHORT \
          --build-arg BUILD_DATE=$(date -u +"%Y-%m-%dT%TZ") \
          /github/home

        buildah manifest push --all koncepts quay.io/$REPO_NAME

        skopeo copy --multi-arch all docker://quay.io/$REPO_NAME docker://docker.io/$REPO_NAME