name: Container image build and publish

on:
  push:
    branches:
    - main
    paths:
    - content/**
    - Dockerfile
    - src/**
    - requirements.txt
    - .github/**

env:
  IMAGE_NAME: koncepts
  TARGET_PLATFORMS: linux/amd64,linux/arm/v7 #,linux/arm64

jobs:

  build:

    runs-on: ubuntu-latest
# will switch to container build later
#    container: quay.io/containers/buildah

    steps:
    - uses: actions/checkout@v3
    - name: build
      run: |
        export REPO_NAME=srowley/$IMAGE_NAME:latest
        export COMMIT_SHA_SHORT=$(echo $GITHUB_SHA | cut -c-7)
        export BUILDKIT_HOST="docker-container://buildkitd"

        docker container run --rm --privileged multiarch/qemu-user-static --reset -p yes
        docker container run -d --rm --name buildkitd --privileged moby/buildkit:latest
        sudo docker container cp buildkitd:/usr/bin/buildctl /usr/local/bin/

        echo ${{secrets.DOCKERHUB_PASSWORD}} | docker login -u ${{secrets.DOCKERHUB_USERNAME}} --password-stdin

        buildctl build \
        --progress=plain \
        --frontend=dockerfile.v0 \
        --local context=. \
        --local dockerfile=. \
        --opt filename=Dockerfile \
        --opt platform=$TARGET_PLATFORMS \
        --opt build-arg:VCS_REF=$COMMIT_SHA_SHORT \
        --opt build-arg:BUILD_DATE=$(date -u +"%Y-%m-%dT%TZ") \
        --output type=image,name=$REPO_NAME,push=true

        curl -X POST https://hooks.microbadger.com/images/srowley/koncepts/4-r475y3YNArRtLbhWpS-CeHghI=
