name: build

on:
  push:
    branches:
    - main
    paths:
    - content/**
    - Dockerfile
    - src/**
    - requirements.txt
    - .github/**

env:
  IMAGE_NAME: srowley/koncepts:latest

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: build
      run: |
        sudo apt-get install -y buildah skopeo qemu-user-static

        export COMMIT_SHA_SHORT=$(echo $GITHUB_SHA | cut -c-7)

        echo Build image name: $IMAGE_NAME
        echo Commit SHA: $COMMIT_SHA_SHORT

        echo "${{secrets.QUAY_PASSWORD}}" | buildah login -u ${{secrets.QUAY_USERNAME}} --password-stdin quay.io

        buildah manifest create koncepts

        buildah bud \
          --tag quay.io/$IMAGE_NAME \
          --manifest koncepts \
          --arch amd64 \
          --file Dockerfile \
          --build-arg VCS_REF=$COMMIT_SHA_SHORT \
          --build-arg BUILD_DATE=$(date -u +"%Y-%m-%dT%TZ") \
          .

        buildah bud \
          --tag quay.io/$IMAGE_NAME \
          --manifest koncepts \
          --arch arm \
          --file Dockerfile \
          --build-arg VCS_REF=$COMMIT_SHA_SHORT \
          --build-arg BUILD_DATE=$(date -u +"%Y-%m-%dT%TZ") \
          .

        buildah manifest push --all koncepts quay.io/$IMAGE_NAME