apiVersion: apps/v1
kind: Deployment
metadata:
  name: koncepts
spec:
  template:
    spec:
      containers:
      - name: koncepts
        env:
        - name: CONTENT_PATH
          value: /etc/myapp/tls
        volumeMounts:
        - name: tls-volume
          mountPath: /etc/myapp/tls
      volumes:
      - name: tls-volume
        secret:
          secretName: tls-certs